YourDressing/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using X.PagedList;
using YourDressing.Models;
using YourDressing.Models.ViewModels;
using YourDressing.Repositories.Interfaces;

namespace YourDressing.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly ISectionRepository _sectionRepository;

        public EmployeesController(IEmployeeRepository employeeService, ISectionRepository sectionService)
        {
            _employeeRepository = employeeService;
            _sectionRepository = sectionService;
        }

        public async Task<IActionResult> Index(int? page, string searchString)
        {
            List<Employee> employees;
            if (string.IsNullOrWhiteSpace(searchString))
                employees = await _employeeRepository.GetAllAsync();
            else
            {
                employees = await _employeeRepository.FindByNameAsync(searchString);
                ViewBag.SearchString = searchString;
            }

            return View(await employees.ToPagedListAsync(page ?? 1, 5));
        }

        public async Task<IActionResult> MonthEmployees(int? page)
        {
            List<Employee> employees = await _employeeRepository.GetMonthEmployeesAsync();
            return View(await employees.ToPagedListAsync(page ?? 1, 5));
        }

        public async Task<IActionResult> FiredEmployees(int? page)
        {
            List<Employee> employees = await _employeeRepository.GetFiredEmployeesAsync();
            return View(employees.ToPagedList(page ?? 1, 5));
        }

        public async Task<IActionResult> Create()
        {
            return View(new EmployeeInputViewModel(await _sectionRepository.GetAllAsync()));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                await _employeeRepository.InsertAsync(employee);
                return RedirectToAction(nameof(Index));
            }

            return View(new EmployeeInputViewModel(employee, await _sectionRepository.GetAllAsync()));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            Employee employee = new();
            try
            {
                employee = await _employeeRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(new EmployeeInputViewModel(employee, await _sectionRepository.GetAllAsync()));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Employee employee)
        {
            if (ModelState.IsValid)
            {
                await _employeeRepository.UpdateAsync(employee);
                return RedirectToAction(nameof(Index));
            }

            return View(new EmployeeInputViewModel(await _sectionRepository.GetAllAsync()));
        }

        public async Task<IActionResult> Details(int? id)
        {
            Employee employee = new();
            try
            {
                employee = await _employeeRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(employee);
        }

        public async Task<IActionResult> EmployeeSales(int? id, int? page)
        {
            try
            {
                Employee employee = await _employeeRepository.FindByIdAsync(id);
                ViewBag.EmployeeName = employee.Name;
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            List<Sale> sales = await _employeeRepository.GetEmployeeSalesAsync(id.Value);
            return View(await sales.ToPagedListAsync(page ?? 1, 10));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            Employee employee = new();
            try
            {
                employee = await _employeeRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _employeeRepository.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error(string message)
        {
            string requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return View(new ErrorViewModel(requestId,  message));
        }
    }
}

YourDressing/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using X.PagedList;
using YourDressing.Models;
using YourDressing.Models.ViewModels;
using YourDressing.Repositories.Interfaces;

namespace YourDressing.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ISectionRepository _sectionRepository;

        public ProductsController(IProductRepository productRepository, ISectionRepository sectionRepository)
        {
            _productRepository = productRepository;
            _sectionRepository = sectionRepository;
        }

        public async Task<IActionResult> Index(int? page, string searchString)
        {
            List<Product> products;
            if (string.IsNullOrWhiteSpace(searchString))
                products = await _productRepository.GetAllAsync();
            else
            {
                products = await _productRepository.FindByNameAsync(searchString);
                ViewBag.SearchString = searchString;
            }

            return View(products.ToPagedList(page ?? 1, 9));
        }

        public async Task<IActionResult> Create()
        {
            return View(new ProductInputViewModel(await _sectionRepository.GetAllAsync()));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                await _productRepository.InsertAsync(product);
                return RedirectToAction(nameof(Index));
            }

            return View(new ProductInputViewModel(product, await _sectionRepository.GetAllAsync()));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                Product product = await _productRepository.FindByIdAsync(id);
                return View(new ProductInputViewModel(product, await _sectionRepository.GetAllAsync()));
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                await _productRepository.UpdateAsync(product);
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                Product product = await _productRepository.FindByIdAsync(id.Value);
                return View(product);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Product product)
        {
            await _productRepository.RemoveAsync(product);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error(string message)
        {
            string requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return View(new ErrorViewModel(requestId, message));
        }
    }
}

YourDressing/Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using X.PagedList;
using YourDressing.Models;
using YourDressing.Models.ViewModels;
using YourDressing.Repositories.Interfaces;

namespace YourDressing.Controllers
{
    public class SalesController : Controller
    {
        private readonly ISaleRepository _saleRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IProductRepository _productRepository;

        public SalesController(ISaleRepository saleRepository, IEmployeeRepository employeeRepository,
            IProductRepository productRepository)
        {
            _saleRepository = saleRepository;
            _employeeRepository = employeeRepository;
            _productRepository = productRepository;
        }

        public async Task<IActionResult> Index(int? page)
        {
            List<Sale> sales = await _saleRepository.GetAllAsync();

            return View(sales.ToPagedList(page ?? 1, 5));
        }

        public async Task<IActionResult> InitialInfos()
        {
            return View(new SelectList(await _employeeRepository.GetAllAsync(), "Id", "Name"));
        }

        [HttpPost]
        public IActionResult InitialInfos(int employeeId, int itemsQuantity)
        {
            return RedirectToAction(nameof(Create), new { employeeId, itemsQuantity });
        }

        public async Task<IActionResult> Create(int employeeId, int itemsQuantity)
        {
            Sale sale = new()
            {
                Employee = await _employeeRepository.FindByIdAsync(employeeId),
                EmployeeId = employeeId
            };
            for (int productsCount = 0; productsCount < itemsQuantity; productsCount++)
            {
                sale.OrderProducts.Add(null);
            }

            SelectList selectList = new(await _productRepository.FindBySectionAsync(sale.Employee.SectionId), 
                "Id", "Name");

            return View(new SaleInputViewModel(sale, itemsQuantity, selectList));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Sale sale)
        {
            if (ModelState.IsValid)
            {
                await _saleRepository.InsertAsync(sale);
                return RedirectToAction(nameof(Index));
            }

            int itemsQuantity = sale.OrderProducts.Count;
            SelectList selectList = new(await _productRepository.FindBySectionAsync(sale.Employee.SectionId));

            SaleInputViewModel viewModel = new(sale, itemsQuantity, selectList);
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                Sale sale = await _saleRepository.FindByIdAsync(id);

                SelectList selectList = new(await _productRepository.GetAllAsync(), "Id", "Name");
                return View(new SaleInputViewModel(sale, sale.OrderProducts.Count, selectList));
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Sale sale)
        {
            if (ModelState.IsValid)
            {
                await _saleRepository.UpdateAsync(sale);
                return RedirectToAction(nameof(Index));
            }

            SelectList selectList = new(await _productRepository.GetAllAsync(), "Id", "Name");
            return View(new SaleInputViewModel(sale, sale.OrderProducts.Count, selectList));
        }

        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                Sale sale = await _saleRepository.FindByIdAsync(id);
                return View(sale);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                Sale sale = await _saleRepository.FindByIdAsync(id);
                return View(sale);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _saleRepository.RemoveAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error(string message)
        {
            string requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return View(new ErrorViewModel(requestId, message));
        }
    }
}

YourDressing/Views/Shared/_EmployeesPartial.cshtml
@model IEnumerable<Employee>

<table class="table table-bordered table-striped text-center">
    <thead>
        <tr class="table-dark">
            <th scope="row">@Html.DisplayNameFor(model => model.First().Name)</th>
            <th>@Html.DisplayNameFor(model => model.First().Section.Name)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Employee employee in Model)
        {
            <tr>
                <td class="text-center">@employee.Name</td>
                <td class="text-center">@employee.Section.Name</td>
                <td class="text-center">
                    <a asp-controller="Employees" asp-action="Details"
                       asp-route-id="@employee.Id" class="text-dark text-decoration-underline" style="text-decoration: none">Detalhes</a>
                    <a asp-controller="Employees" asp-action="Edit" asp-route-id="@employee.Id" 
                        class="text-dark text-decoration-underline" style="text-decoration: none">Editar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

YourDressing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Your Dressing</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-lux.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Your Dressing</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Employees" asp-action="Index">Funcionários</a>
                        </li>
                        <li class="nav-item dropdown">
                            @await Component.InvokeAsync("SectionMenu"); 
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Products" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Sales" asp-action="Index">Vendas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <wbr />
            <h1>@ViewData["Title"]</h1>
            <h5>@ViewData["Subtitle"]</h5>

            <wbr />

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Powered by Douglas Vitor &copy;
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

YourDressing/Views/Shared/_SalesPartial.cshtml
@model IPagedList<Sale>

<table class="table table-striped table-bordered text-center">
    <thead>
        <tr class="table-dark">
            <th scope="row">@Html.DisplayNameFor(model => model.First().Id)</th>
            <th>@Html.DisplayNameFor(model => model.First().TotalPrice)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Sale sale in Model)
        {
            <tr>
                <td>@sale.Id</td>
                <td>@sale.TotalPrice.ToString("C2", CultureInfo.CurrentCulture)</td>
                <td>
                    <a class="text-dark text-decoration-underline" style="text-decoration: none" asp-controller="Sales" asp-action="Details" asp-route-id="@sale.Id">Detalhes</a>
                </td>
            </tr>
        }
    </tbody>
</table>

YourDressing/Views/Shared/_SectionEmployeesPartial.cshtml
@model IPagedList<Employee>

<table class="table table-striped table-bordered">
    <thead class="table-dark text-center">
        <tr>
            <th scope="row">@Html.DisplayNameFor(model => model.First().Name)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody class="text-center">
        @foreach (Employee employee in Model)
        {
            <tr>
                <td>@employee.Name</td>
                <td>
                    <a asp-controller="Employees" asp-action="Details" asp-route-id="@employee.Id" class="text-dark text-decoration-underline" style="text-decoration: none">Detalhes</a>
                    <a asp-controller="Employees" asp-action="Edit" asp-route-id="@employee.Id" class="text-dark text-decoration-underline" style="text-decoration: none">Editar</a>
                </td>
            </tr>
        }
    </tbody>
</table>