YourDressing/Models/Section.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using YourDressing.Models.Enums;

namespace YourDressing.Models
{
    public class Section : Entity
    {
        [DisplayName("Seção")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "O campo {0} deve conter entre {2} e {1} caracteres.")]
        [MaxLength(100)]
        public string Name { get; set; }

        [DisplayName("Descrição")]
        [StringLength(100, MinimumLength = 10, ErrorMessage = "O campo {0} deve conter entre {2} e {1} caracteres.")]
        [MaxLength(300)]
        public string Description { get; set; }

        [DisplayName("Situação")]
        public SectionSituation Situation { get; set; }

        public virtual List<Employee> Employees { get; set; } = new();
        public virtual List<Product> Products { get; set; } = new();

        public Section()
        {
        }

        public Section(string name, string description)
        {
            Name = name;
            Description = description;
        }

        public void AddEmployee(Employee employee)
        {
            Employees.Add(employee);
        }

        public void AddEmployees(params Employee[] employees)
        {
            if (employees is null)
                return;

            Employees.AddRange(employees);
        }

        public void AddProduct(Product product)
        {
            Products.Add(product);
        }

        public void AddProducts(params Product[] products)
        {
            if (products is null)
                return;

            Products.AddRange(products);
        }

        public double GetTotalProfit()
        {
            double totalProfit = 0;
            foreach (Employee employeeProfit in Employees)
            {
                totalProfit += employeeProfit.GetEmployeeTotalProfit();
            }

            return totalProfit;
        }
    }
}

YourDressing/Controllers/SectionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;
using YourDressing.Models;
using YourDressing.Models.ViewModels;
using YourDressing.Repositories.Interfaces;

namespace YourDressing.Controllers
{
    public class SectionController : Controller
    {
        private readonly ISectionRepository _sectionRepository;

        public SectionController(ISectionRepository sectionRepository)
        {
            _sectionRepository = sectionRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _sectionRepository.GetAllAsync());
        }
        
        public async Task<IActionResult> Disabled()
        {
            return View(await _sectionRepository.GetDisabledSectionsAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionRepository.InsertAsync(section);
                return RedirectToAction(nameof(Index));
            }

            return View(section);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            Section section = new();
            try
            {
                section = await _sectionRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionRepository.UpdateAsync(section);
                return RedirectToAction(nameof(Index));
            }

            return View(section);
        }

        public async Task<IActionResult> Details(int? id)
        {
            return View(await _sectionRepository.FindByIdAsync(id));
        }

        public async Task<IActionResult> SectionEmployees(int id, int? page)
        {
            List<Employee> employees = await _sectionRepository.GetSectionEmployees(id);

            Section _ = await _sectionRepository.FindByIdAsync(id);
            ViewBag.SectionName = _.Name.ToLower();

            return View(await employees.ToPagedListAsync(page ?? 1, 5));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            Section section = new();
            try
            {
                section = await _sectionRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Section section)
        {
            await _sectionRepository.RemoveAsync(section);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error(string message)
        {
            string requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return View(new ErrorViewModel(requestId, message));
        }
    }
}

YourDressing/Controllers/SectionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using X.PagedList;
using YourDressing.Models;
using YourDressing.Repositories.Interfaces;

namespace YourDressing.Controllers
{
    public class SectionsController : Controller
    {
        private readonly ISectionRepository _sectionRepository;

        public SectionsController(ISectionRepository sectionRepository)
        {
            _sectionRepository = sectionRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _sectionRepository.GetAllAsync());
        }
        
        public async Task<IActionResult> Disabled()
        {
            return View(await _sectionRepository.GetDisabledSectionsAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionRepository.InsertAsync(section);
                return RedirectToAction(nameof(Index));
            }

            return View(section);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            Section section = new();
            try
            {
                section = await _sectionRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionRepository.UpdateAsync(section);
                return RedirectToAction(nameof(Index));
            }

            return View(section);
        }

        public async Task<IActionResult> Details(int? id)
        {
            return View(await _sectionRepository.FindByIdAsync(id));
        }

        public async Task<IActionResult> SectionEmployees(int? id, int? page)
        {
            try
            {
                Section section = await _sectionRepository.FindByIdAsync(id);
                ViewBag.SectionName = section.Name.ToLower();
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            List<Employee> employees = await _sectionRepository.GetSectionEmployeesAsync(id.Value);
            return View(await employees.ToPagedListAsync(page ?? 1, 5));
        }

        public async Task<IActionResult> SectionSales(int? id, int? page)
        {
            try
            {
                Section section = await _sectionRepository.FindByIdAsync(id);
                ViewBag.SectionName = section.Name.ToLower();
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            List<Sale> sales = await _sectionRepository.GetSectionSalesAsync(id.Value);
            return View(await sales.ToPagedListAsync(page ?? 1, 10));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            Section section = new();
            try
            {
                section = await _sectionRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _sectionRepository.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error(string message)
        {
            string requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return View(new ErrorViewModel(requestId, message));
        }
    }
}

YourDressing/Views/Sections/Create.cshtml
@model Section

@{ 
    ViewData["Title"] = "Administração de seções";
    ViewBag.Subtitle2 = "Criar nova seção";
}

<h3>@ViewBag.Subtitle2</h3>

<div class="row">
    <div class="col-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly"></div>

            <div class="form-group">
                <label asp-for="@Model.Name" class="col-form-label mt-4"></label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Description" class="col-form-label mt-4"></label>
                <input asp-for="@Model.Description" class="form-control" />
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>

            <div>
                <a class="btn btn-outline-dark" style="float:right" asp-action="Index">Cancelar</a>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-success" value="Confirmar" style="float:right" />
            </div>
        </form>
    </div>
</div>

YourDressing/Views/Sections/Delete.cshtml
@model Section

@{
    ViewData["Title"] = "Administração de funcionários";
    ViewBag.Subtitle2 = "Excluir seção: você tem certeza?";
}

<h3>@ViewBag.Subtitle2</h3>

<div class="container">
    <div class="col-10" style="display:inline-block">
        <form asp-action="Delete">
            <div class="form-group">
                <label asp-for="Name" class="col-form-label mt-4"></label>
                <input asp-for="Name" class="form-control" type="text" style="width: 250px" placeholder="@Model.Name" readonly="" />
            </div>

            <div class="form-group">
                <label asp-for="Description" class="col-form-label mt-4"></label>
                <input asp-for="Description" class="form-control" type="text" placeholder="@Model.Description" readonly="" />
            </div>

            <wbr />
            <div>
                <a class="btn btn-outline-dark" style="float:right;" asp-action="Index">Cancelar</a>
            </div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" />
                <input type="submit" class="btn btn-success" value="Confirmar" style="float:right" />
            </div>
        </form>
    </div>
</div>

<p class="text-info">
    Importante: Esta seção não será removida dos registros caso tenha funcionários ou vendas atreladas a 
    ela, mas será tratada como inoperante. Caso isso ocorra, você poderá encontrá-la neste sistema e, 
    eventualmente, reativá-la. Esta é uma ação cautelosa para manter a integridade de outros dados.
</p>

YourDressing/Views/Sections/Details.cshtml
@model Section

@{
    ViewData["Title"] = "Administração de funcionários";
    ViewBag.Subtitle2 = "Detalhes da seção";
}

<div class="container" style="display: inline-block">
    <h3 style="float: left">@ViewBag.Subtitle2</h3>
    <a asp-action="SectionSales" class="btn btn-info" style="float: right" asp-route-id="@Model.Id">Vendas dessa seção</a>
    <a asp-action="SectionEmployees" class="btn btn-info" style="float:right" asp-route-id="@Model.Id">Funcionários dessa seção</a>
</div>

<div class="row">
    <div class="col-10">
        <label asp-for="@Model.Name" class="col-form-label mt-4"></label>
        <input class="form-control" style="width:250px" type="text" placeholder="@Model.Name" readonly="" />

        <label asp-for="@Model.Description" class="col-form-label mt-4"></label>
        <input class="form-control" type="text" readonly="" placeholder="@Model.Description" />

        <label asp-for="@Model.Situation" class="col-forml-label mt-4"></label>
        <input class="form-control" type="text" readonly="" placeholder="@EnumExtensions.GetDescription(Model.Situation)" />

        <label class="col-form-label mt-4">Lucro da seção:</label>
        <div class="input-group mb-3">
            <span class="input-group-text">R$</span>
            <input class="form-control" placeholder="@Model.GetTotalProfit()" readonly="" />
            <span class="input-group-text">,00</span>
        </div>

        <a asp-action="Index" class="btn btn-outline-dark" style="float: right">Voltar</a>
        <a asp-action="Edit" class="btn btn-success" style="float:right" asp-route-id="@Model.Id">Editar</a>
    </div>
</div>

YourDressing/Views/Sections/Disabled.cshtml
@model IEnumerable<Section>

@{ 
    ViewData["Title"] = "Administração de seções";
    ViewBag.Subtitle2 = "Seções desativadas";
}

<div class="row">
    <div class="container" style="display: inline-block">
        <h3 style="float: left">@ViewBag.Subtitle2</h3>
        <a asp-action="Index" class="btn btn-outline-dark" style="float: right">Todas as seções</a>
    </div>
</div>

<table class="table table-bordered table-striped text-center">
    <thead>
        <tr class="table-dark">
            <th scope="row">@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Description)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Section item in Model)
        {
            <tr>
                <td class="text-center">@item.Name</td>
                <td class="text-center" style="max-width:450px">@item.Description</td>
                <td class="text-center">
                    <a asp-action="Details" asp-route-id="@item.Id" class="text-dark text-decoration-underline" style="text-decoration: none">Detalhes</a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="text-dark text-decoration-underline" style="text-decoration: none">Editar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

YourDressing/Views/Sections/Edit.cshtml
@model Section

@{ 
    ViewData["Title"] = "Administração de seções";
    ViewBag.Subtitle2 = "Editar seção";
}

<h3>@ViewBag.Subtitle2</h3>

<div class="row">
    <div class="col-8">
        <form asp-action="Edit">
            <input type="hidden" asp-for="@Model.Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="@Model.Name" class="col-form-label mt-4"></label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Description" class="col-form-label mt-4"></label>
                <input asp-for="@Model.Description" class="form-control" />
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                @if (Model.Situation is SectionSituation.Disabled)
                {
                    <label asp-for="Situation" class="col-form-label mt-4"></label>
                    <select asp-for="Situation" asp-items="Html.GetEnumSelectList<SectionSituation>()"
                            class="form-control"></select>
                }
            </div>

            <div class="form-group">
                <a class="btn btn-outline-dark" style="float: right" asp-action="Index">Cancelar</a>
            </div>
            <div>
                <input type="submit" class="btn btn-success" value="Confirmar" style="float: right" />
            </div>
        </form>
    </div>
</div>

YourDressing/Views/Sections/Index.cshtml
@model IEnumerable<Section>

@{ 
    ViewData["Title"] = "Administração de seções";
    ViewBag.Subtitle2 = "Lista de seções";
}

<div class="row">
    <div class="container" style="display: inline-block">
        <h3 style="float: left">@ViewBag.Subtitle2</h3>
        <a class="btn btn-danger" style="float:right" asp-action="Disabled">Seções desativadas</a>
        <a class="btn btn-outline-dark" style="float: right" asp-controller="Sections" asp-action="Create">
            Criar nova
        </a>
    </div>
</div>

<div class="row">
    <table class="table table-bordered table-striped text-center">
        <thead>
            <tr class="table-dark">
                <th scope="row">@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Section item in Model)
            {
            <tr>
                <td class="text-center">@item.Name</td>
                <td class="text-center" style="max-width: 400px">@item.Description</td>
                <td class="text-center">
                    <a class="text-dark text-decoration-underline" style="text-decoration: none" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                    <a class="text-dark text-decoration-underline" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                    <a class="text-dark text-decoration-underline" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

YourDressing/Views/Sections/SectionEmployees.cshtml
@model IPagedList<Employee>

@{ 
    ViewData["Title"] = "Administração de seções";
    ViewBag.Subtitle2 = $"Funcionários da seção: {ViewBag.SectionName}";
} 

<h3>@ViewBag.Subtitle2</h3>

<div class="row">
    <partial name="_SectionEmployeesPartial" for="@Model" />
</div>

<div class="container" style="display:inline-block">
    <h5 style="float:left">Página @Model.PageNumber de @Model.PageCount</h5>
    @Html.PagedListPager(@Model, page => Url.Action("SectionEmployees", new { page = page }), 
        Bootstrap4PagedListRenderOptions.Classic)
</div>

YourDressing/Views/Sections/SectionSales.cshtml
@model IPagedList<Sale>

@{
    ViewData["Title"] = "Administração de seções";
    ViewBag.Subtitle2 = $"Vendas da seção: {ViewBag.SectionName}";
}

<h3>@ViewBag.Subtitle2</h3>

<div class="row">
    <partial name="_SalesPartial" for="@Model" />
</div>

@if (Model.PageCount > 1)
{
<div class="container" style="display:inline-block">
    <h5 style="float:left">Página @Model.PageNumber de @Model.PageCount</h5>
    @Html.PagedListPager(@Model, page => Url.Action("SectionEmployees", new { page = page }),
            Bootstrap4PagedListRenderOptions.Classic)
</div>
}