YourDressing/Models/Section.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using YourDressing.Models.Enums;

namespace YourDressing.Models
{
    public class Section : Entity
    {
        [DisplayName("Seção")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "O campo {0} deve conter entre {2} e {1} caracteres.")]
        [MaxLength(100)]
        public string Name { get; set; }

        [DisplayName("Descrição")]
        [StringLength(100, MinimumLength = 10, ErrorMessage = "O campo {0} deve conter entre {2} e {1} caracteres.")]
        [MaxLength(300)]
        public string Description { get; set; }

        [DisplayName("Situação")]
        public SectionSituation Situation { get; set; }

        public virtual List<Employee> Employees { get; set; } = new();
        public virtual List<Product> Products { get; set; } = new();

        public Section()
        {
        }

        public Section(string name, string description)
        {
            Name = name;
            Description = description;
        }

        public void AddEmployee(Employee employee)
        {
            Employees.Add(employee);
        }

        public void AddEmployees(params Employee[] employees)
        {
            if (employees is null)
                return;

            Employees.AddRange(employees);
        }

        public void AddProduct(Product product)
        {
            Products.Add(product);
        }

        public void AddProducts(params Product[] products)
        {
            if (products is null)
                return;

            Products.AddRange(products);
        }

        public double GetTotalProfit()
        {
            double totalProfit = 0;
            foreach (Employee employeeProfit in Employees)
            {
                totalProfit += employeeProfit.GetEmployeeTotalProfit();
            }

            return totalProfit;
        }
    }
}

YourDressing/Controllers/SectionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;
using YourDressing.Models;
using YourDressing.Models.ViewModels;
using YourDressing.Repositories.Interfaces;

namespace YourDressing.Controllers
{
    public class SectionController : Controller
    {
        private readonly ISectionRepository _sectionRepository;

        public SectionController(ISectionRepository sectionRepository)
        {
            _sectionRepository = sectionRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _sectionRepository.GetAllAsync());
        }
        
        public async Task<IActionResult> Disabled()
        {
            return View(await _sectionRepository.GetDisabledSectionsAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionRepository.InsertAsync(section);
                return RedirectToAction(nameof(Index));
            }

            return View(section);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            Section section = new();
            try
            {
                section = await _sectionRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionRepository.UpdateAsync(section);
                return RedirectToAction(nameof(Index));
            }

            return View(section);
        }

        public async Task<IActionResult> Details(int? id)
        {
            return View(await _sectionRepository.FindByIdAsync(id));
        }

        public async Task<IActionResult> SectionEmployees(int id, int? page)
        {
            List<Employee> employees = await _sectionRepository.GetSectionEmployees(id);

            Section _ = await _sectionRepository.FindByIdAsync(id);
            ViewBag.SectionName = _.Name.ToLower();

            return View(await employees.ToPagedListAsync(page ?? 1, 5));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            Section section = new();
            try
            {
                section = await _sectionRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Section section)
        {
            await _sectionRepository.RemoveAsync(section);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error(string message)
        {
            string requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return View(new ErrorViewModel(requestId, message));
        }
    }
}

YourDressing/Controllers/SectionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using X.PagedList;
using YourDressing.Models;
using YourDressing.Repositories.Interfaces;

namespace YourDressing.Controllers
{
    public class SectionsController : Controller
    {
        private readonly ISectionRepository _sectionRepository;

        public SectionsController(ISectionRepository sectionRepository)
        {
            _sectionRepository = sectionRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _sectionRepository.GetAllAsync());
        }
        
        public async Task<IActionResult> Disabled()
        {
            return View(await _sectionRepository.GetDisabledSectionsAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionRepository.InsertAsync(section);
                return RedirectToAction(nameof(Index));
            }

            return View(section);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            Section section = new();
            try
            {
                section = await _sectionRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionRepository.UpdateAsync(section);
                return RedirectToAction(nameof(Index));
            }

            return View(section);
        }

        public async Task<IActionResult> Details(int? id)
        {
            return View(await _sectionRepository.FindByIdAsync(id));
        }

        public async Task<IActionResult> SectionEmployees(int? id, int? page)
        {
            try
            {
                Section section = await _sectionRepository.FindByIdAsync(id);
                ViewBag.SectionName = section.Name.ToLower();
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            List<Employee> employees = await _sectionRepository.GetSectionEmployeesAsync(id.Value);
            return View(await employees.ToPagedListAsync(page ?? 1, 5));
        }

        public async Task<IActionResult> SectionSales(int? id, int? page)
        {
            try
            {
                Section section = await _sectionRepository.FindByIdAsync(id);
                ViewBag.SectionName = section.Name.ToLower();
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            List<Sale> sales = await _sectionRepository.GetSectionSalesAsync(id.Value);
            return View(await sales.ToPagedListAsync(page ?? 1, 10));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            Section section = new();
            try
            {
                section = await _sectionRepository.FindByIdAsync(id);
            }
            catch (ApplicationException error)
            {
                return RedirectToAction(nameof(Error), new { message = error.Message });
            }

            return View(section);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _sectionRepository.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error(string message)
        {
            string requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            return View(new ErrorViewModel(requestId, message));
        }
    }
}

YourDressing/Views/Section/Create.cshtml
@model Section

@{ 
    ViewData["Title"] = "Administração de seções";
    ViewBag.Subtitle2 = "Criar nova seção";
}

<h3>@ViewBag.Subtitle2</h3>

<div class="row">
    <div class="col-5">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly"></div>

            <div class="form-group">
                <label asp-for="@Model.Name" class="col-form-label mt-4"></label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Description" class="col-form-label mt-4"></label>
                <input asp-for="@Model.Description" class="form-control" />
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>

            <div>
                <a class="btn btn-outline-dark" style="float:right" asp-action="Index">Cancelar</a>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-success" value="Confirmar" style="float:right" />
            </div>
        </form>
    </div>
</div>

YourDressing/Views/Section/Edit.cshtml
@model Section

@{ 
    ViewData["Title"] = "Administração de seções";
    ViewBag.Subtitle2 = "Editar seção";
}

<h3>@ViewBag.Subtitle2</h3>

<div class="row">
    <div class="col-5">
        <form asp-action="Edit">
            <input type="hidden" asp-for="@Model.Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="@Model.Name" class="col-form-label mt-4"></label>
                <input asp-for="@Model.Name" class="form-control" />
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Description" class="col-form-label mt-4"></label>
                <input asp-for="@Model.Description" class="form-control" />
                <span asp-validation-for="@Model.Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                @if (Model.Situation is SectionSituation.Disabled)
                {
                    <label asp-for="Situation" class="col-form-label mt-4"></label>
                    <select asp-for="Situation" asp-items="Html.GetEnumSelectList<SectionSituation>()"
                            class="form-control"></select>
                }
            </div>

            <div class="form-group">
                <a class="btn btn-outline-dark" style="float: right" asp-action="Index">Cancelar</a>
            </div>
            <div>
                <input type="submit" class="btn btn-success" value="Confirmar" style="float: right" />
            </div>
        </form>
    </div>
</div>

YourDressing/Views/Section/Index.cshtml
@model IEnumerable<Section>

@{ 
    ViewData["Title"] = "Administração de seções";
    ViewBag.Subtitle2 = "Lista de seções";
}

<div class="row">
    <div class="container" style="display: inline-block">
        <h3 style="float: left">@ViewBag.Subtitle2</h3>
        <a class="btn btn-danger" style="float:right" asp-action="Disabled">Seções desativadas</a>
        <a class="btn btn-outline-dark" style="float: right" asp-controller="Section" asp-action="Create">
            Criar nova
        </a>
    </div>
</div>

<div class="row">
    <table class="table table-bordered table-striped text-center">
        <thead>
            <tr class="table-dark">
                <th scope="row">@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Section item in Model)
            {
            <tr>
                <td class="text-center">@item.Name</td>
                <td class="text-center" style="max-width: 400px">@item.Description</td>
                <td class="text-center">
                    <a class="text-dark text-decoration-underline" style="text-decoration: none" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                    <a class="text-dark text-decoration-underline" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                    <a class="text-dark text-decoration-underline" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>